name: Multi-lang CI/CD
run-name: Event | ${{ github.event_name }}
permissions:
  contents: write
  pull-requests: write

on: 
  workflow_dispatch:
  push: 
   branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
   
     
jobs:
  Dev-Stage:
    uses: pkseaws/repo-b/.github/workflows/reusable-workflow.yml@main
    with:
       upload_artifact: true
       terraform_dir: terraform
    secrets: inherit
  
 
