name: Multi-lang CI/CD
permissions:
  contents: write
  pull-requests: write

on: 
  workflow_dispatch:
  push: 
   branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
   
     
jobs:
  Dev-Stage:
  #  strategy: #
   #    matrix:
    #     language: [java, python]
     #    env: [dev, stage]
    
    
    ##if: github.event_name == 'pull_request'
    uses: pkseaws/repo-b/.github/workflows/reusable-workflow.yml@main
    with:
     #  language: ${{ matrix.language }}
      # env: ${{ matrix.env }}
       upload_artifact: true
       terraform_dir: terraform
    secrets: inherit
  
  # Dev-Stage:
  #   strategy:
  #     matrix:
  #       language: [java, python]
  #       env: [dev, stage]
  #   if: github.event_name == 'pull_request'
  #   uses: pkseaws/repo-b/.github/workflows/reusable-workflow.yml@main
  #   with:
  #     language: ${{ matrix.language }}
  #     env: ${{ matrix.env }}
  #     upload_artifact: true
  #     terraform_dir: terraform
  #   secrets: inherit

  # build-prod:
  #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
  #   strategy:
  #     matrix:
  #       language: [java, python]
  #   uses: pkseaws/repo-b/.github/workflows/reusable-workflow.yml@main
  #   with:
  #     language: ${{ matrix.language }}
  #     env: prod
  #     upload_artifact: true
  #     terraform_dir: terraform
  #   secrets: inherit

  # terraform-workflow:
  #     if: github.event_name == 'workflow_dispatch'
  #     uses: pkseaws/repo-b/.github/workflows/reusable-workflow.yml@main
  #     with:
  #       terraform_dir: terraform
  #       upload_artifact: false
  #     secrets: inherit
     
