name: Multi-lang CI/CD

on: 
  workflow_dispatch:
  #push: 
   #branches: [main]
  #pull_request:
   # types: [opened, synchronize, reopened]
     inputs:
       terraform_dir:
         required: false
         type: string
     
jobs:
  Dev-Stage:
    strategy:
      matrix:
        language: [java, python]
        env: [dev, stage]
    if: github.event_name == 'pull_request'
    uses: pkseaws/repo-b/.github/workflows/reusable-workflow.yml@main
    with:
      language: ${{ matrix.language }}
      env: ${{ matrix.env }}
      upload_artifact: true
    secrets: inherit

  build-prod:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    strategy:
      matrix:
        language: [java, python]
    uses: pkseaws/repo-b/.github/workflows/reusable-workflow.yml@main
    with:
      language: ${{ matrix.language }}
      env: prod
      upload_artifact: true
    secrets: inherit

  terraform-workflow:
      #if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      #strategy:
       # matrix:
        #  language: [java, python]
         # env: [dev, stage]
      uses: pkseaws/repo-b/.github/workflows/reusable-workflow.yml@main
      with:
        #language: ${{ matrix.language }}
        #env: ${{ matrix.env }}
        terraform_dir: terraform
        upload_artifact: false
      secrets: inherit
      #secrets:
       # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        #AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
